-- V1__baseline.sql
-- Initial database schema for TaskManager
-- Generated by Trabuco

-- Placeholders table (example entity)
CREATE TABLE placeholders (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for name lookups
CREATE INDEX idx_placeholders_name ON placeholders(name);

-- Add your additional tables below
-- Example:
-- CREATE TABLE your_entity (
--     id BIGSERIAL PRIMARY KEY,
--     ...
-- );
